name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run make
      run: make
    - name: Strip binary
      run: strip target/release/libspotifyadblock.so
    - name: Create build artifact
      uses: actions/upload-artifact@v3
      with:
        name: spotify-adblock.so
        path: target/release/libspotifyadblock.so
